import type { Address } from "viem";
import { goldRewardsAbi, goldTokenAbi, minerFiNFTAbi } from "./abis";
import deployments from "./deployments.json";

/**
 * Contract addresses come from a committed JSON file that `npm run
 * contracts:deploy` writes, not from environment variables.
 *
 * The tradeoff is deliberate: env vars mean a fresh clone renders a broken app
 * until somebody finds the right values, and it is never obvious which chain a
 * given address belongs to. A file keyed by chain id makes "which contracts is
 * this build pointing at" answerable by reading one file, and lets a single
 * build serve both the local chain and the testnet.
 *
 * Note the ABIs are re-exported with their literal `as const` types intact
 * rather than widened to `Abi`. That is what lets wagmi infer argument and
 * return types for every read and write, so a contract change surfaces as a
 * typecheck failure instead of `undefined` at runtime.
 */

type DeploymentRecord = {
  chainId: number;
  deployedAt: string;
  deployer: string;
  blockNumber: number;
  contracts: {
    goldToken: string;
    minerFiNft: string;
    goldRewards: string;
  };
};

const RECORDS = deployments as Record<string, DeploymentRecord>;

/** Chain ids the contracts have actually been deployed to. */
export const DEPLOYED_CHAIN_IDS = Object.keys(RECORDS).map(Number);

/**
 * Returns null rather than throwing when nothing is deployed for the chain.
 * A wallet pointed at the wrong network is an ordinary state the UI has to
 * render, not an exception.
 */
export function getContracts(chainId: number | undefined) {
  if (chainId === undefined) return null;

  const record = RECORDS[String(chainId)];
  if (!record) return null;

  return {
    chainId: record.chainId,
    deployedAt: record.deployedAt,
    nft: record.contracts.minerFiNft as Address,
    gold: record.contracts.goldToken as Address,
    rewards: record.contracts.goldRewards as Address,
  };
}

export type ContractSet = NonNullable<ReturnType<typeof getContracts>>;

/* abis.ts is generated by `npm run contracts:compile` and names its exports
   after the Solidity contracts, so `MinerFiNFT` comes out as `minerFiNFTAbi`.
   Renamed once here rather than everywhere it is consumed — regenerating the
   file must not churn the rest of the app. */
export { goldRewardsAbi, goldTokenAbi, minerFiNFTAbi as minerFiNftAbi };
